# Generated by Django 4.2.2 on 2023-06-25 16:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('alternance', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='offre',
            fields=[
                ('id_offre', models.BigAutoField(primary_key=True, serialize=False)),
                ('poste', models.CharField(max_length=50, unique=True)),
                ('contrat', models.CharField(max_length=50)),
                ('entreprise', models.CharField(max_length=50)),
                ('localisation', models.CharField(max_length=50)),
                ('details', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alternance.users')),
            ],
        ),
    ]
