# Generated by Django 4.2.2 on 2023-06-25 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alternance', '0002_offre'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Users',
            new_name='User',
        ),
        migrations.RenameField(
            model_name='offre',
            old_name='contrat',
            new_name='choix_contrat',
        ),
    ]
